-- V1__create_schema.sql

CREATE TABLE TIPOS_IDENTIFICACION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE PACIENTES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    TIPO_IDENTIFICACION BIGINT NOT NULL,
    IDENTIFICACION VARCHAR(50) NOT NULL,

    CONSTRAINT FK_PACIENTE_TIPO_IDENTIFICACION
        FOREIGN KEY (TIPO_IDENTIFICACION)
        REFERENCES TIPOS_IDENTIFICACION(ID)
);

CREATE TABLE MEDICO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    TIPO_IDENTIFICACION BIGINT NOT NULL,
    IDENTIFICACION VARCHAR(50) NOT NULL,
    SEXO VARCHAR(10),

    CONSTRAINT FK_MEDICO_TIPO_IDENTIFICACION
        FOREIGN KEY (TIPO_IDENTIFICACION)
        REFERENCES TIPOS_IDENTIFICACION(ID)
);

CREATE TABLE SIGNOS_VITALES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PACIENTE_ID BIGINT NOT NULL,
    PRESION_SISTOLICA INT,
    PRESION_DIASTOLICA INT,
    FRECUENCIA_CARDIACA INT,
    TEMPERATURA DECIMAL(4,2),
    SATURACION_OXIGENO INT,
    FECHA_HORA TIMESTAMP NOT NULL,

    CONSTRAINT FK_SIGNOS_PACIENTE
        FOREIGN KEY (PACIENTE_ID)
        REFERENCES PACIENTES(ID)
);

CREATE TABLE OBSERVACIONES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SIGNO_VITAL_ID BIGINT NOT NULL,
    MEDICO_ID BIGINT NOT NULL,
    MENSAJE TEXT,
    FECHA TIMESTAMP NOT NULL,

    CONSTRAINT FK_OBSERVACION_SIGNO
        FOREIGN KEY (SIGNO_VITAL_ID)
        REFERENCES SIGNOS_VITALES(ID),

    CONSTRAINT FK_OBSERVACION_MEDICO
        FOREIGN KEY (MEDICO_ID)
        REFERENCES MEDICO(ID)
);

CREATE INDEX IDX_PACIENTE_IDENTIFICACION
ON PACIENTES(IDENTIFICACION);

CREATE INDEX IDX_SIGNOS_PACIENTE
ON SIGNOS_VITALES(PACIENTE_ID);

CREATE INDEX IDX_OBSERVACIONES_SIGNO
ON OBSERVACIONES(SIGNO_VITAL_ID);